### ISSUE TITLE
IONIC production build issue

### ISSUE THREAD

**Issue by jaymehtasa** [yajuve/ng-input-password#1]
When I build ionic project w/o `--prod` flag it works fine, but w/ `--prod` flag it throws following error.

```
[16:27:06]  typescript error
            Unexpected value 'NgInputPasswordComponent in
            /Projects/PWA/GTHub/git/gt-hub-app-pwa/node_modules/ng-input-password/ng-input-password.d.ts' declared by
            the module 'AppModule in /Projects/PWA/GTHub/git/gt-hub-app-pwa/src/app/app.module.ts'. Please add a
            @Pipe/@Directive/@Component annotation.

[16:27:06]  ionic-app-script task: "build"
[16:27:06]  Error: The Angular AoT build failed. See the issues above
Error: The Angular AoT build failed. See the issues above
    at /Projects/PWA/GTHub/git/gt-hub-app-pwa/node_modules/@ionic/app-scripts/dist/aot/aot-compiler.js:237:55
    at step (/Projects/PWA/GTHub/git/gt-hub-app-pwa/node_modules/@ionic/app-scripts/dist/aot/aot-compiler.js:32:23)
    at Object.next (/Projects/PWA/GTHub/git/gt-hub-app-pwa/node_modules/@ionic/app-scripts/dist/aot/aot-compiler.js:13:53)
    at fulfilled (/Projects/PWA/GTHub/git/gt-hub-app-pwa/node_modules/@ionic/app-scripts/dist/aot/aot-compiler.js:4:58)
    at <anonymous>
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! gt-hub@0.0.1 build:stage: `GT_ENV=stage ionic-app-scripts build`
npm ERR! Exit status 1
```

**Comment by yajuve** [comment]
Hi,
Please update to version 3.0.0
`
npm i ng-input-password@3.0.0
`
Best regards
